---@meta

--- Experimental options.
---@class markview.config.experimental
---
---@field check_rtp boolean Whether to scan the `runtimepath` for errors & potentially fixing them.
---@field check_rtp_message boolean Whether to shoe message if `nvim-treesitter` gets loaded before `markview.nvim`.
---
---@field date_formats string[] List of lua patterns for detecting date in YAML.
---@field date_time_formats string[] List of lua patterns for detecting date & time in YAML.
---
---@field prefer_nvim boolean Opens text file inside Neovim.
---@field file_open_command string Command used to open files inside Neovim.
---
---@field list_empty_line_tolerance integer Maximum number of empty lines that can stay between text of a list item.
---
---@field read_chunk_size integer Number of `bytes` to check before opening a link. Used for detecting when to open files inside Neovim.
---
---@field linewise_ignore_org_indent? boolean Prevents indentation of sections from being cleared in `linewise_hybrid_mode`.
