---@meta

---@class markview.config.asciidoc.document_titles
---
---@field enable boolean
---
---@field sign? string
---@field sign_hl? string
---
---@field icon? string
---@field icon_hl? string
---
---@field hl? string
