---@meta

---@class markview.config.experimental
---
---@field date_formats string[] String formats for detecting date in YAML.
---@field date_time_formats string[] String formats for detecting date & time in YAML.
---
---@field prefer_nvim boolean Opens text file inside Neovim.
---@field file_open_command string Command used to open files inside Neovim.
---
---@field list_empty_line_tolerance integer Maximum number of empty lines that can stay between text of a list item.
---
---@field read_chunk_size integer Number of `bytes` to check before opening a link. Used for detecting when to open files inside Neovim.
