---@meta

---@class markview.config.preview
---
---@field enable? boolean Enables *preview* when attaching to new buffers.
---@field enable_hybrid_mode? boolean Enables `hybrid mode` when attaching to new buffers.
---
---@field callbacks? markview.config.preview.callbacks Callback functions.
---
---@field map_gx? boolean  Whether to map `gx` to custom URL opener.
---
---@field debounce? integer Debounce delay for updating previews.
--- Icon provider.
---@field icon_provider?
---| "" Disable icons.
---| "internal" Internal icon provider.
---| "devicons" `nvim-web-devicons` as icon provider.
---| "mini" `mini.icons` as icon provider.
---
---@field modes? string[] VIM-modes where previews will be shown.
---@field hybrid_modes? string[] VIM-modes where `hybrid mode` is enabled. Options that should/shouldn't be previewed in `hybrid_modes`.
---
---@field ignore_previews? preview.ignore
--- Clear lines around the cursor in `hybrid mode`, instead of nodes?
---@field linewise_hybrid_mode? boolean
--- Buffer filetypes where the plugin should attach.
---@field filetypes? string[]
--- Buftypes that should be ignored(e.g. nofile).
---@field ignore_buftypes? string[]
--- Condition to check if a buffer should be attached or not.
---@field condition? fun(buffer: integer): boolean
--- Maximum number of lines a buffer can have before switching to partial rendering.
---@field max_buf_lines? integer
---
--- Lines before & after the cursor that is considered being edited.
--- Edited content isn't rendered.
---@field edit_range? [ integer, integer ]
--- Lines before & after the cursor that is considered being previewed.
---@field draw_range? [ integer, integer ]
---
--- Window options for the `splitview` window.
--- See `:h nvim.open_win()`.
---@field splitview_winopts? table


--- Callback functions for specific events.
---@class markview.config.preview.callbacks
---
---@field on_attach? fun(buf: integer, wins: integer[]): nil Called when attaching to a buffer.
---@field on_detach? fun(buf: integer, wins: integer[]): nil Called when detaching from a buffer.
---
---@field on_disable? fun(buf: integer, wins: integer[]): nil Called when disabling preview of a buffer. Also called when using `splitOpen`.
---@field on_enable? fun(buf: integer, wins: integer[]): nil Called when enabling preview of a buffer. Also called when using `splitClose`.
---
---@field on_hybrid_disable? fun(buf: integer, wins: integer[]): nil Called when disabling hybrid mode in a buffer.
---@field on_hybrid_enable? fun(buf: integer, wins: integer[]): nil Called when enabling hybrid mode in a buffer.
---
---@field on_mode_change? fun(buf: integer, wins: integer[], mode: string): nil Called when changing VIM-modes(only on active buffers).
---
---@field on_splitview_close? fun(source: integer, preview_buf: integer, preview_win: integer): nil Called before closing splitview.
---@field on_splitview_open? fun(source: integer, preview_buf: integer, preview_win: integer): nil Called when opening splitview.


--- Items to ignore when rendering.
---@class preview.ignore
---
---@field html? ignore_html[]
---@field latex? ignore_latex[]
---@field markdown? ignore_md[]
---@field markdown_inline? ignore_inline[]
---@field typst? ignore_typst[]
---@field yaml? ignore_yaml[]

---@alias ignore_html
---| "!container_elements"
---| "!headings"
---| "!void_elements"
---
---| "container_elements"
---| "headings"
---| "void_elements"

---@alias ignore_latex
---| "!blocks"
---| "!commands"
---| "!escapes"
---| "!fonts"
---| "!inlines"
---| "!parenthesis"
---| "!subscripts"
---| "!superscripts"
---| "!symbols"
---| "!texts"
---
---| "blocks"
---| "commands"
---| "escapes"
---| "fonts"
---| "inlines"
---| "parenthesis"
---| "subscripts"
---| "superscripts"
---| "symbols"
---| "texts"

---@alias ignore_md
---| "!block_quotes"
---| "!code_blocks"
---| "!headings"
---| "!horizontal_rules"
---| "!list_items"
---| "!metadata_minus"
---| "!metadata_plus"
---| "!reference_definitions"
---| "!tables"
---
---| "block_quotes"
---| "code_blocks"
---| "headings"
---| "horizontal_rules"
---| "list_items"
---| "metadata_minus"
---| "metadata_plus"
---| "reference_definitions"
---| "tables"
---
---| "checkboxes"

---@alias ignore_inline
---| "!block_references"
---| "!checkboxes"
---| "!emails"
---| "!embed_files"
---| "!entities"
---| "!escapes"
---| "!footnotes"
---| "!highlights"
---| "!hyperlinks"
---| "!images"
---| "!inline_codes"
---| "!internal_links"
---| "!uri_autolinks"
---
---| "block_references"
---| "checkboxes"
---| "emails"
---| "embed_files"
---| "entities"
---| "escapes"
---| "footnotes"
---| "highlights"
---| "hyperlinks"
---| "images"
---| "inline_codes"
---| "internal_links"
---| "uri_autolinks"

---@alias ignore_typst
---| "!code_blocks"
---| "!code_spans"
---| "!escapes"
---| "!headings"
---| "!labels"
---| "!list_items"
---| "!math_blocks"
---| "!math_spans"
---| "!raw_blocks"
---| "!raw_spans"
---| "!reference_links"
---| "!subscripts"
---| "!superscripts"
---| "!symbols"
---| "!terms"
---| "!url_links"
---
---| "code_blocks"
---| "code_spans"
---| "escapes"
---| "headings"
---| "labels"
---| "list_items"
---| "math_blocks"
---| "math_spans"
---| "raw_blocks"
---| "raw_spans"
---| "reference_links"
---| "subscripts"
---| "superscripts"
---| "symbols"
---| "terms"
---| "url_links"

---@alias ignore_yaml
---| "!properties"
---
---| "properties"

